

[sncast.default]                                         
url = "https://starknet-sepolia.infura.io/v3/*****"
accounts-file = "~/.starknet_accounts/starknet_open_zeppelin_accounts.json"
account = "account_braavos"

[sncast.mainnet]
account = "account_braavos_mainnet"
accounts-file = "~/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "https://starknet-mainnet.infura.io/v3/******"